### ISSUE TITLE
[BUG] can open books

### ISSUE THREAD

**Issue by Borzoff** [ACK72/kavya-paperback#11]
I can't open the books, saw the closed issuse but still haven't figured out how to fix the error
![image](https://github.com/ACK72/kavya-paperback/assets/59200516/d6898906-400b-4896-af1a-2f4b5f248d7f)

**Comment by ACK72** [comment]
It looks like you're trying to open a file type that isn't supported by Paperback.
Currently, Paperback "only" supports "image file types" like JPG and PNG,
so you won't be able to view book-related file types like EPUBs uploaded to Kavita with Paperback, even with other plugins.
