### ISSUE TITLE
[BUG] All manga showing the wrong time they were added

### ISSUE THREAD

**Issue by blitz4694** [ACK72/kavya-paperback#12]
**Describe the bug**
All manga show as being added from 2 years ago to 7000 years ago, even though they were added recently.

**Screenshots**
<img width="667" alt="Screenshot 2023-10-23 at 7 02 51 pm jpeg" src="https://github.com/ACK72/kavya-paperback/assets/17425938/845dcb29-e5cf-4acf-9854-936ba5bb16aa">

**Comment by ACK72** [comment]
I've fixed that bug and now show the time since the item was created or released.
If it doesn't work after the update, try uninstalling and reinstalling Paperback.
