### ISSUE TITLE
[Question] How to work with multiple instances?

### ISSUE THREAD

**Issue by JJGO** [ACK72/kavya-paperback#13]
I wanted to check if there is a way to add multiple Kavita instances using this plugin, or to replicate the plugin to achieve that functionality. 

Guidance is much appreciated, and thanks so much for this great Kavita-paperback extension!

**Comment by ACK72** [comment]
Sorry for late reply.
You can use multiple Kavita instance by creating multiple Kavya extensions.

To do this, fork this repository and change the "Kavya" of 48th line of Kavya.ts to something else you want.
then, edit "https://ack72.github.io/kavya-paperback" of README.md to "https://JJGO.github.io/kavya-paperback".

Add that repository to your paperback, and you can connect other Kavita instances to it.
