### ISSUE TITLE
Decimal chapters skipped

### ISSUE THREAD

**Issue by IsXGeo** [ACK72/kavya-paperback#5]
**Describe the bug**
I have chapters labelled 'Chapter 11, Chapter 11.5, Chapter 12' however in paperback it displays as such 'Chapter 11, Chapter 11, Chapter 12' thereby skipping chapter 11.5

**Expected behavior**
The extension should recognise decimal point chapters 

**Screenshots**
The chapters in Kavita
![image](https://user-images.githubusercontent.com/16053230/232178744-2ceff45c-5089-40ca-87a6-461c33d56092.jpeg)

The chapters in paperback
![image](https://user-images.githubusercontent.com/16053230/232178751-77cb4ee6-8c5c-4eeb-969d-8b352c661420.jpeg)

**Comment by ACK72** [comment]
It will be recognized correctly with Kavya 1.2.6.
Thanks for your issue report.

**Comment by IsXGeo** [comment]
Thanks for the swift fix! Appreciate it.
