### ISSUE TITLE
[BUG] Images not showing

### ISSUE THREAD

**Issue by therobbiedavis** [ACK72/kavya-paperback#7]
**Describe the bug**
Images not showing with Kavya 1.2.7 and Kavita 0.7.1.44

**Screenshots**
![image](https://user-images.githubusercontent.com/7907265/235358744-d44273c5-597d-4406-92bc-c8ea8a284eb7.png)

```
[ERROR] [2023-04-30T14:54:50.569Z] [PagedChapterRenderer:loadImage(from:into:pageIndex:):861] The HTTP status code in response is invalid. Code: 400, response: <NSHTTPURLResponse: 0x2817fd480> { URL: https://kavita.therobbiedavis.com/api/Reader/image?chapterId=107342&page=1&apiKey=https://kavita.therobbiedavis.com/api&extractPdf=true

```

**Comment by ACK72** [comment]
Thank you for your report
Found a typo in the code and fixed it.
